### ISSUE TITLE
Documentation on setting up a development enviroment

### ISSUE THREAD

**Issue by pszeder** [samartzidis/RaspiKey#11]
First of all, thank you for your great work!
I've been using RaspiKey on one of my computers daily for the past 2 years and it has been great!

Now I would like to have a go at improving it and it would be great if you could provide some details on how to set up the development environment.

Thank you!

**Comment by samartzidis** [comment]
There is some documentation on that here: https://github.com/samartzidis/RaspiKey/blob/master/raspikey/README.md

**Comment by pszeder** [comment]
Ahh, I haven't seen that one! Thank you!
