### ISSUE TITLE
Issue with unselected "Swap Fn-Ctrl'

### ISSUE THREAD

**Issue by verity-s** [samartzidis/RaspiKey#4]
By default, "Swap Fn-Ctrl" is enabled. If it's deselected, pressing Fn creates a locked/stuck Fn key on my A1644. Enabling the swap with the mouse resolves the Fn lock. Since I don't intend to use those two keys swapped, could this be resolved, please?

**Comment by vipwp** [comment]
I fixed it.
https://github.com/vipwp/RaspiKey/commit/c9237d462c04cc0197dad7357b9e42e74c7f2fc5#diff-33e56b858e5dfb0de56eb24685796cbe

**Comment by brnhrdt** [comment]
> I fixed it.
> [vipwp@c9237d4#diff-33e56b858e5dfb0de56eb24685796cbe](https://github.com/vipwp/RaspiKey/commit/c9237d462c04cc0197dad7357b9e42e74c7f2fc5#diff-33e56b858e5dfb0de56eb24685796cbe)

Maybe you could create a merge requests, so this issue is fixed in the next release? Thanks!

**Comment by jwoglom** [comment]
@vipwp can you publish a release in your forked version of the library? I am running into the same problem and would love to try out your fix, but don't want to have to manually compile everything on my machine.

**Comment by samartzidis** [comment]
@jwoglom I am currently working on a new build. Will be out soon.

**Comment by samartzidis** [comment]
Merged @vipwp 's changes into the new release [raspikey-setup.2.3.182+2afb446](https://github.com/samartzidis/RaspiKey/releases/tag/raspikey-setup.2.3.182%2B2afb446).
The setup process is slightly different, please check [updated setup notes](https://github.com/samartzidis/RaspiKey#setting-up-a-new-raspikey-device).
Cheers.
