### ISSUE TITLE
Support pass-thru of Magic Trackpad in addition to Magic Keyboard

### ISSUE THREAD

**Issue by jwoglom** [samartzidis/RaspiKey#6]
It would be amazing if I could pair my Magic Trackpad 2 to RaspiKey in addition to my keyboard, so that I could pass-thru the mouse to my computer as well. I realize that this would be a significant expansion in scope of this project, but it would be convenient to not need to plug in my trackpad to my computer with a Lightning cable when my keyboard can connect via bluetooth to the Pi Zero.

**Comment by samartzidis** [comment]
I do not currently have the plans and time for investing into something like this but I will keep your suggestion in my "nice to have" feature list.  In the meantime, this project may be of interest to you: **https://github.com/imbushuo/mac-precision-touchpad** 
Thank you!
