### ISSUE TITLE
New version 2.3.x doesn't work

### ISSUE THREAD

**Issue by brnhrdt** [samartzidis/RaspiKey#7]
I just followed the updated installation steps (raspios) and tried to install new versions 2.3.201 and 2.3.195. Unfortunately none of them worked. I can't access the url http://169.254.1.1 after installation is done. This works fine with raspbian + version 1.2.5.

**Comment by samartzidis** [comment]
Apologies @brnhrdt, the setup instructions were wrong (they were asking you to use the old **raspbian-stretch-lite** image). Can you please try again following the updated setup instructions? Thank you!

**Comment by brnhrdt** [comment]
Thanks for you fast response. Actually I just managed to run the new version 2.3.201 using the raspios. I made a dumb mistake previously and used wrong cable (why are manufacturer even make usb cables that ONLY meant for charging 🤬)

Thank you a lot for this amazing project!!
